name: Update All Proxies

on:
  schedule:
    - cron: '8 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install node-fetch@2

      - name: Run Main Scraper & Ping Check
        run: node index.js

      - name: Run Converter (V2Ray + Sing-Box)
        run: node convert.js  

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto Update: Scrape, Ping & Convert Proxies $(date)" || exit 0
          git push
