name: Update All Proxies

on:
  schedule:
    - cron: '8 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: |
          npm install node-fetch@2 js-yaml

      - name: Run Main Scraper & Ping Check
        run: node index.js

      - name: Download Mihomo (Clash Meta) core for testing
        run: |
          wget https://github.com/MetaCubeX/mihomo/releases/download/v1.18.3/mihomo-linux-amd64-v1.18.3.gz
          gunzip mihomo-linux-amd64-v1.18.3.gz
          mv mihomo-linux-amd64-v1.18.3 ./mihomo
          chmod +x mihomo

      - name: Run Aggressive Speed Tester (Clash)
        run: node tester.js

      # تبدیل رو بعد از تست کردن فایل all.yaml انجام میدیم تا فقط سرورهای تمیز وارد سینگ‌باکس بشن
      - name: Run Converter (V2Ray + Sing-Box)
        run: node convert.js  
      
      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto Update: Scrape, Ping, Test & Convert Proxies $(date)" || exit 0
          git pull --rebase origin main
          git push
